### ISSUE TITLE
void constructor not available

### ISSUE THREAD

**Issue by KanLok78** [leftCoast/LC_blockFile#1]
hi,

I would like to use your classLC_blockFile, but I can't find the void constructor for the class.

how can I create object of the class as global variable? when i try to create global variable like this: blockFile bFile(fileName);
I get error message file not open and getFileHeader returns false. (Although file is present and open in SD card).

I assume it is because when creating new object of blockFile it tries to initialize it and open it without SD card being initialized, and that is why the error.

Any suggestions how to create an object and work with blockFile Class.

Thanks & Regards,
Lokesh

**Comment by leftCoast** [comment]
So did you give up on it? Or figure out why there was no void constructor? I assume you figured it out because you starred it. Thanks for the star by the way.

To set up a global, Define a global pointer to your blockFile object then in the code, when things are running, allocate your object dynamically. 

-jim lee
